# Generated by Django 5.2.17 on 2026-09-26 01:55

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('room', 'Habitación'), ('bathroom', 'Baño'), ('property', 'Propiedad'), ('accessibility', 'Accesibilidad'), ('view', 'Vista')], default='room', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.CharField(choices=[('room_type', 'Categoría'), ('room', 'Habitación'), ('guest', 'Huésped'), ('reservation', 'Reserva')], max_length=20)),
                ('key', models.SlugField()),
                ('label', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Sí/No'), ('select', 'Lista'), ('multiselect', 'Lista múltiple'), ('date', 'Fecha')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('show_in_marketplace', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='core.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='core.property')),
            ],
            options={
                'ordering': ['applies_to', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('building', models.CharField(blank=True, max_length=50)),
                ('overrides', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('custom_values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('housekeeping_status', models.CharField(choices=[('clean', 'Limpia'), ('dirty', 'Sucia'), ('inspected', 'Inspeccionada'), ('out_of_service', 'Fuera de servicio')], default='clean', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('connecting_rooms', models.ManyToManyField(blank=True, to='inventory.room')),
                ('extra_amenities', models.ManyToManyField(blank=True, related_name='rooms_with_extra', to='inventory.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.property')),
                ('removed_amenities', models.ManyToManyField(blank=True, related_name='rooms_without', to='inventory.amenity')),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Sencilla'), ('bunk_top', 'Camarote (arriba)'), ('bunk_bottom', 'Camarote (abajo)'), ('double', 'Doble')], default='single', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inventory.room')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kind', models.CharField(choices=[('out_of_order', 'Fuera de orden'), ('out_of_service', 'Fuera de servicio'), ('maintenance', 'Mantenimiento'), ('owner_hold', 'Uso del propietario')], default='out_of_order', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='inventory.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='inventory.room')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('description', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('kind', models.CharField(choices=[('private', 'Privada'), ('dorm', 'Dormitorio (venta por cama)')], default='private', max_length=10)),
                ('base_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('beds', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('size_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('view', models.CharField(blank=True, max_length=50)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('accessible', models.BooleanField(default=False)),
                ('color', models.CharField(default='#4E6C88', max_length=7)),
                ('housekeeping_minutes', models.PositiveSmallIntegerField(default=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='inventory.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='core.property')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='inventory.roomtype'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('caption', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.room')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='amenity_code_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'property', 'applies_to', 'key'), name='custom_field_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='bed_label_unique'),
        ),
        migrations.AddIndex(
            model_name='roomblock',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='room_block_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='room_block_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='room_type_code_unique'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property', 'housekeeping_status'], name='room_property_hk_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'number'), name='room_number_unique'),
        ),
    ]
