# Generated by Django 5.2.17 on 2026-09-26 01:55

import apps.bookings.models
import django.contrib.postgres.constraints
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('guests', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('contact_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_groups', to='guests.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_groups', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('tentative', 'Tentativa'), ('confirmed', 'Confirmada'), ('checked_in', 'En casa'), ('checked_out', 'Salió'), ('cancelled', 'Cancelada'), ('no_show', 'No show')], default='confirmed', max_length=20)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Teléfono'), ('email', 'Email'), ('front_desk', 'Recepción'), ('booking_engine', 'Motor de reservas'), ('marketplace', 'Marketplace'), ('ota', 'OTA'), ('api', 'API')], default='front_desk', max_length=20)),
                ('channel_code', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('external_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('language', models.CharField(default='es', max_length=5)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('guarantee', models.CharField(choices=[('none', 'Sin garantía'), ('card', 'Tarjeta'), ('deposit', 'Depósito'), ('ota', 'OTA')], default='none', max_length=10)),
                ('cancellation_policy_snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custom_values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tags', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='guests.guest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.property')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='bookings.reservationgroup')),
            ],
            options={
                'ordering': ['-checkin_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('children_ages', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('nightly_rates', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('tentative', 'Tentativa'), ('confirmed', 'Confirmada'), ('checked_in', 'En casa'), ('checked_out', 'Salió'), ('cancelled', 'Cancelada'), ('no_show', 'No show')], default='confirmed', max_length=20)),
                ('locked_room', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stays', to='inventory.bed')),
                ('occupants', models.ManyToManyField(blank=True, related_name='stays', to='guests.guest')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stays', to='rates.rateplan')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='bookings.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stays', to='inventory.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stays', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['checkin_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('sold_units', models.PositiveIntegerField(default=0)),
                ('blocked_units', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_days', to='core.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_days', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['property', 'date'], name='inventory_day_prop_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('room_type', 'date'), name='inventory_day_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'checkin_date'], name='reservation_prop_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'checkout_date'], name='reservation_prop_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'status'], name='reservation_prop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'channel_code', 'external_id'], name='reservation_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('checkout_date__gt', models.F('checkin_date'))), name='reservation_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['room_type', 'checkin_date', 'checkout_date'], name='stay_type_range_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['room', 'checkin_date'], name='stay_room_checkin_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('checkout_date__gt', models.F('checkin_date'))), name='stay_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('bed__isnull', True), ('room__isnull', False), ('status__in', ['tentative', 'confirmed', 'checked_in'])), expressions=[(apps.bookings.models.DateRangeFunc('checkin_date', 'checkout_date', models.Value('[)')), '&&'), ('room', '=')], name='stay_no_room_overlap'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('bed__isnull', False), ('status__in', ['tentative', 'confirmed', 'checked_in'])), expressions=[(apps.bookings.models.DateRangeFunc('checkin_date', 'checkout_date', models.Value('[)')), '&&'), ('bed', '=')], name='stay_no_bed_overlap'),
        ),
    ]
