# Generated by Django 5.2.17 on 2026-09-28 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryday',
            name='held_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Teléfono'), ('email', 'Email'), ('front_desk', 'Recepción'), ('booking_engine', 'Motor de reservas'), ('marketplace', 'Marketplace'), ('ota', 'OTA'), ('api', 'API'), ('import', 'Importación')], default='front_desk', max_length=20),
        ),
        migrations.CreateModel(
            name='GroupBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('units', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bookings.reservationgroup')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_blocks', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['start', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='stay',
            name='group_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='bookings.groupblock'),
        ),
        migrations.AddIndex(
            model_name='groupblock',
            index=models.Index(fields=['room_type', 'start', 'end'], name='group_block_type_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='group_block_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 1)), name='group_block_units_positive'),
        ),
    ]
