# Generated by Django 5.2.17 on 2026-09-27 07:04

import apps.housekeeping.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stayover_frequency_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('require_inspection', models.BooleanField(default=False)),
                ('auto_assign', models.BooleanField(default=True)),
                ('minutes_per_shift', models.PositiveSmallIntegerField(default=420, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(900)])),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_settings', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'housekeeping settings',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En curso'), ('resolved', 'Resuelto'), ('cancelled', 'Cancelado')], default='open', max_length=20)),
                ('blocks_room', models.BooleanField(default=False)),
                ('blocked_until', models.DateField(blank=True, null=True)),
                ('room_status_before', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.roomblock')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='core.property')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='inventory.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(max_length=255, storage=apps.housekeeping.storage.PrivateMediaStorage(), upload_to=apps.housekeeping.storage.ticket_photo_upload_to)),
                ('content_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='housekeeping.maintenanceticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('departure_clean', 'Limpieza de salida'), ('stayover', 'Repaso'), ('deep_clean', 'Limpieza profunda'), ('inspection', 'Inspección'), ('turndown', 'Cobertura nocturna'), ('custom', 'Otra tarea')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('done', 'Terminada'), ('inspected', 'Inspeccionada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('business_date', models.DateField()),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_source', models.CharField(choices=[('checkout', 'Check-out'), ('status_change', 'Habitación marcada sucia'), ('daily', 'Generación diaria'), ('inspection', 'Inspección'), ('manual', 'Manual'), ('seed', 'Datos de demostración')], default='manual', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='inventory.bed')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='core.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to='bookings.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='inventory.room')),
            ],
            options={
                'ordering': ['business_date', 'created_at'],
                'indexes': [models.Index(fields=['property', 'business_date'], name='hk_task_property_date_idx'), models.Index(fields=['assigned_to', 'business_date'], name='hk_task_assignee_date_idx'), models.Index(fields=['room', 'status'], name='hk_task_room_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ['departure_clean', 'stayover']), ('status__in', ['pending', 'in_progress'])), fields=('room',), name='hk_one_open_turnover_per_room')],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['property', 'status'], name='hk_ticket_property_status_idx'),
        ),
    ]
