# Generated by Django 5.2.17 on 2026-09-27 07:06

import apps.marketplace.models
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEngineSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to=apps.marketplace.models._engine_upload)),
                ('hero_image', models.ImageField(blank=True, upload_to=apps.marketplace.models._engine_upload)),
                ('headline', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('show_promo_field', models.BooleanField(default=True)),
                ('min_advance_hours', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(720)])),
                ('max_advance_days', models.PositiveSmallIntegerField(default=365, validators=[django.core.validators.MaxValueValidator(730)])),
                ('terms', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('allowed_rate_plans', models.ManyToManyField(blank=True, related_name='+', to='rates.rateplan')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_engine', to='core.property')),
            ],
            options={
                'verbose_name': 'booking engine settings',
                'verbose_name_plural': 'booking engine settings',
            },
        ),
        migrations.CreateModel(
            name='ListingContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagline', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('highlights', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='core.property')),
            ],
            options={
                'verbose_name': 'listing content',
                'verbose_name_plural': 'listing contents',
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_photos', to='marketplace.listingcontent')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.photo')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='listingcontent',
            name='featured_photos',
            field=models.ManyToManyField(blank=True, related_name='+', through='marketplace.ListingPhoto', to='inventory.photo'),
        ),
        migrations.AddConstraint(
            model_name='listingphoto',
            constraint=models.UniqueConstraint(fields=('listing', 'photo'), name='listing_photo_unique'),
        ),
    ]
