# Generated by Django 5.2.17 on 2026-09-27 07:02

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('occupancy', 'Ocupación'), ('lead_time', 'Anticipación'), ('day_of_week', 'Día de la semana'), ('holiday', 'Festivos y puentes'), ('event', 'Evento')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('combine', models.CharField(choices=[('stack', 'Sumar'), ('max', 'Máximo')], default='stack', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='core.property')),
                ('room_types', models.ManyToManyField(blank=True, related_name='pricing_rules', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('automation', 'Programada'), ('manual', 'Manual'), ('seed', 'Datos de demo')], default='automation', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recommendations_count', models.PositiveIntegerField(default=0)),
                ('auto_applied_count', models.PositiveIntegerField(default=0)),
                ('expired_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ai_summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ai_provider', models.CharField(blank=True, max_length=40)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_runs', to='core.property')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_apply', models.BooleanField(default=False)),
                ('horizon_days', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)])),
                ('max_daily_change_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_change_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('price_rounding', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_settings', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'revenue settings',
            },
        ),
        migrations.CreateModel(
            name='PriceBounds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bounds', to='rates.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bounds', to='inventory.roomtype')),
            ],
            options={
                'verbose_name_plural': 'price bounds',
                'ordering': ['rate_plan__sort_order', 'room_type__sort_order', 'room_type__code'],
                'constraints': [models.UniqueConstraint(fields=('room_type', 'rate_plan'), name='price_bounds_unique'), models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('min_price__lte', models.F('max_price')), _connector='OR'), name='price_bounds_min_lte_max')],
            },
        ),
        migrations.CreateModel(
            name='RateRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_source', models.CharField(blank=True, max_length=20)),
                ('anchor_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('anchor_source', models.CharField(blank=True, max_length=20)),
                ('adjustment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=7)),
                ('occupancy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_units', models.IntegerField(blank=True, null=True)),
                ('reasons', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('explanation', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('applied', 'Aplicada'), ('auto_applied', 'Aplicada automáticamente'), ('expired', 'Vencida')], default='pending', max_length=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.CharField(blank=True, max_length=300)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recommendations', to='core.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recommendations', to='rates.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_recommendations', to='inventory.roomtype')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='revenue.revenuerun')),
            ],
            options={
                'ordering': ['date', 'room_type__sort_order', 'room_type__code'],
                'indexes': [models.Index(fields=['property', 'status', 'date'], name='rate_rec_prop_status_date'), models.Index(fields=['room_type', 'rate_plan', 'date'], name='rate_rec_key_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('room_type', 'rate_plan', 'date'), name='rate_recommendation_one_pending')],
            },
        ),
    ]
