import {
  Accessibility,
  AirVent,
  ArrowUpDown,
  Baby,
  Bath,
  BedDouble,
  Bike,
  Building,
  Bus,
  Car,
  ConciergeBell,
  Coffee,
  CookingPot,
  Croissant,
  Dog,
  Dumbbell,
  Fan,
  Fence,
  Flower2,
  GripHorizontal,
  Heater,
  Lamp,
  LampDesk,
  Laptop,
  Leaf,
  Lock,
  Luggage,
  MonitorPlay,
  Moon,
  Mountain,
  Music,
  Plug,
  Refrigerator,
  Shirt,
  ShowerHead,
  SoapDispenserDroplet,
  Sofa,
  Sparkles,
  SquareParking,
  Sun,
  TowelRack,
  TreePalm,
  Trees,
  Tv,
  Users,
  Utensils,
  Vault,
  VolumeX,
  WashingMachine,
  WavesHorizontal,
  WavesLadder,
  Wifi,
  Wind,
  Wine,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons an amenity can use (`Amenity.icon` stores the lucide name in kebab-case). A curated set keeps the
 * bundle small; unknown names fall back to `sparkles`.
 */
export const AMENITY_ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  'air-vent': AirVent,
  'arrow-up-down': ArrowUpDown,
  baby: Baby,
  bath: Bath,
  'bed-double': BedDouble,
  bike: Bike,
  building: Building,
  bus: Bus,
  car: Car,
  'concierge-bell': ConciergeBell,
  coffee: Coffee,
  'cooking-pot': CookingPot,
  croissant: Croissant,
  dog: Dog,
  dumbbell: Dumbbell,
  fan: Fan,
  fence: Fence,
  'flower-2': Flower2,
  'grip-horizontal': GripHorizontal,
  heater: Heater,
  lamp: Lamp,
  'lamp-desk': LampDesk,
  laptop: Laptop,
  leaf: Leaf,
  lock: Lock,
  luggage: Luggage,
  'monitor-play': MonitorPlay,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  plug: Plug,
  refrigerator: Refrigerator,
  shirt: Shirt,
  'shower-head': ShowerHead,
  'soap-dispenser-droplet': SoapDispenserDroplet,
  sofa: Sofa,
  sparkles: Sparkles,
  'square-parking': SquareParking,
  sun: Sun,
  'towel-rack': TowelRack,
  'tree-palm': TreePalm,
  trees: Trees,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  vault: Vault,
  'volume-x': VolumeX,
  'washing-machine': WashingMachine,
  'waves-horizontal': WavesHorizontal,
  'waves-ladder': WavesLadder,
  wifi: Wifi,
  wind: Wind,
  wine: Wine,
}

export const AMENITY_ICON_NAMES = Object.keys(AMENITY_ICONS)

export function amenityIcon(name: string | undefined): LucideIcon {
  return (name && AMENITY_ICONS[name]) || Sparkles
}
