# Generated by Django 5.2.17 on 2026-09-26 01:55

import datetime
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Needed by bookings.Stay ExclusionConstraints (daterange && + uuid =).
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(default='CO', max_length=2)),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activa'), ('past_due', 'En mora'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostal'), ('boutique', 'Hotel boutique'), ('aparthotel', 'Aparthotel'), ('glamping', 'Glamping')], default='hotel', max_length=20)),
                ('description', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CO', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('default_language', models.CharField(default='es', max_length=5)),
                ('check_in_time', models.TimeField(default=datetime.time(15, 0))),
                ('check_out_time', models.TimeField(default=datetime.time(12, 0))),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('rnt_number', models.CharField(blank=True, max_length=30)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('house_rules', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('business_date', models.DateField(default=django.utils.timezone.localdate)),
                ('marketplace_listed', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('branding', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('payments', 'Pagos'), ('channel_ical', 'Canal iCal'), ('channel_channex', 'Channex'), ('einvoice', 'Factura electrónica'), ('sire', 'SIRE'), ('tra', 'TRA'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('llm', 'IA (LLM)'), ('saas_billing', 'Cobro SaaS')], max_length=30)),
                ('mode', models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulado')], default='simulated', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('secrets_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('unknown', 'Desconocido'), ('ok', 'OK'), ('error', 'Error')], default='unknown', max_length=10)),
                ('status_message', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='core.property')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('property', 'kind'), name='integration_setting_unique', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='AutomationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='core.property')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('property', 'code'), name='automation_setting_unique', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('success', 'Éxito'), ('partial', 'Parcial'), ('failed', 'Falló'), ('skipped', 'Omitida')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='core.property')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['property', 'code', '-started_at'], name='automation_run_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('user', 'Usuario'), ('automation', 'Automatización'), ('ai', 'IA'), ('channel', 'Canal'), ('guest', 'Huésped'), ('system', 'Sistema'), ('api', 'API')], default='user', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('reversible', models.BooleanField(default=False)),
                ('undo_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', '-created_at'], name='audit_property_created_idx'), models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['action'], name='audit_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('source', models.CharField(default='system', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'resolved_at'], name='alert_property_resolved_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('property', 'dedupe_key'), name='alert_open_unique', nulls_distinct=False)],
            },
        ),
    ]
