# Generated by Django 5.2.17 on 2026-09-27 07:03

import datetime
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('guests', '0003_unaccent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('web_chat', 'Chat web'), ('ota', 'OTA')], max_length=20)),
                ('external_thread_key', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('last_message_direction', models.CharField(blank=True, max_length=3)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='guests.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='bookings.reservation')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('confirmation', 'Confirmación'), ('pre_arrival', 'Pre-llegada'), ('arrival_day', 'Día de llegada'), ('post_stay', 'Post-estancia'), ('payment_reminder', 'Recordatorio de pago'), ('cancellation', 'Cancelación')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('partial', 'Parcial'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='sent', max_length=10)),
                ('channels', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_dispatches', to='bookings.reservation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('confirmation', 'Confirmación'), ('pre_arrival', 'Pre-llegada'), ('arrival_day', 'Día de llegada'), ('post_stay', 'Post-estancia'), ('payment_reminder', 'Recordatorio de pago'), ('cancellation', 'Cancelación')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('days_offset', models.PositiveSmallIntegerField(default=0)),
                ('channels', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('template_code', models.SlugField(max_length=64)),
                ('send_after', models.TimeField(default=datetime.time(9, 0))),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_rules', to='core.property')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('web_chat', 'Chat web'), ('ota', 'OTA'), ('internal_note', 'Nota interna')], max_length=20)),
                ('sender_label', models.CharField(blank=True, max_length=200)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('received', 'Recibido')], default='queued', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('template_code', models.CharField(blank=True, max_length=64)),
                ('ai_generated', models.BooleanField(default=False)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bookings.reservation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('wa_template_name', models.CharField(blank=True, max_length=512)),
                ('wa_template_params', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', 'channel', 'language'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['property', '-last_message_at'], name='conversation_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_thread_key', ''), _negated=True), fields=('property', 'channel', 'external_thread_key'), name='conversation_thread_unique'),
        ),
        migrations.AddConstraint(
            model_name='lifecycledispatch',
            constraint=models.UniqueConstraint(fields=('reservation', 'event'), name='lifecycle_dispatch_unique'),
        ),
        migrations.AddConstraint(
            model_name='lifecyclerule',
            constraint=models.UniqueConstraint(fields=('property', 'event'), name='lifecycle_rule_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_thread_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('channel', 'provider_message_id'), name='message_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('property', 'code', 'channel', 'language'), name='msg_template_property_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', True)), fields=('organization', 'code', 'channel', 'language'), name='msg_template_org_unique'),
        ),
    ]
