# Generated by Django 5.2.17 on 2026-09-27 07:04

import apps.guestportal.models
import apps.guests.storage
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0002_b4_intents_refunds_cash_shifts'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPortalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_opens_days_before', models.PositiveSmallIntegerField(default=7)),
                ('require_document_photo', models.BooleanField(default=True)),
                ('require_signature', models.BooleanField(default=True)),
                ('auto_approve_extras', models.BooleanField(default=True)),
                ('allow_guest_cancellation', models.BooleanField(default=True)),
                ('allow_guest_modification', models.BooleanField(default=True)),
                ('terms', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_portal_settings', to='core.property')),
            ],
            options={
                'verbose_name': 'guest portal settings',
                'verbose_name_plural': 'guest portal settings',
            },
        ),
        migrations.CreateModel(
            name='OnlineCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Sin empezar'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=20)),
                ('current_step', models.CharField(choices=[('guests', 'Huéspedes'), ('documents', 'Documentos'), ('arrival', 'Llegada'), ('signature', 'Firma y términos'), ('payment', 'Pago'), ('done', 'Listo')], default='guests', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('signature', models.FileField(blank=True, max_length=255, storage=apps.guests.storage.PrivateDocumentStorage(), upload_to=apps.guestportal.models.signature_upload_to)),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_checkin', to='bookings.reservation')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='online_checkin_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('late_checkout', 'Late check-out'), ('early_checkin', 'Early check-in'), ('transfer', 'Traslado'), ('extra', 'Extra'), ('other', 'Otra solicitud')], max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('done', 'Realizada')], default='requested', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.charge')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rates.extra')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='bookings.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='service_request_res_status_idx')],
            },
        ),
    ]
