# Generated by Django 5.2.17 on 2026-09-28 07:41

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0002_b4_intents_refunds_cash_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('received_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Vigente'), ('voided', 'Anulado')], default='active', max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payments', to='core.property')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='corporate.accountpayment')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_allocations', to='finance.folio')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account_allocation', to='finance.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('corporate', 'Corporativo'), ('travel_agency', 'Agencia de viajes'), ('government', 'Entidad pública'), ('other', 'Otro')], default='corporate', max_length=20)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('nit', models.CharField(max_length=15)),
                ('dv', models.CharField(max_length=1)),
                ('vat_responsible', models.BooleanField(default=True)),
                ('tax_responsibilities', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CO', max_length=2)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('credit_enabled', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('contacts', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['legal_name'],
            },
        ),
        migrations.AddField(
            model_name='accountpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_payments', to='corporate.company'),
        ),
        migrations.CreateModel(
            name='ReservationBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_to', models.CharField(choices=[('guest', 'Huésped'), ('company', 'Empresa')], default='guest', max_length=10)),
                ('routing', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('purchase_order', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_billings', to='corporate.company')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='bookings.reservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'is_active'], name='company_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('organization', 'nit'), name='company_org_nit_unique'),
        ),
        migrations.AddIndex(
            model_name='accountpayment',
            index=models.Index(fields=['company', 'property'], name='account_payment_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationbilling',
            constraint=models.CheckConstraint(condition=models.Q(('bill_to', 'guest'), ('company__isnull', False), _connector='OR'), name='billing_company_required'),
        ),
    ]
