# Generated by Django 5.2.17 on 2026-09-26 01:55

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('non_refundable', models.BooleanField(default=False)),
                ('free_until_hours_before', models.PositiveIntegerField(default=48)),
                ('penalty_type', models.CharField(choices=[('first_night', 'Primera noche'), ('percent', 'Porcentaje del total'), ('full', 'Total de la reserva')], default='first_night', max_length=20)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('description', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'cancellation policies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('kind', models.CharField(choices=[('base', 'Base'), ('derived', 'Derivado')], default='base', max_length=10)),
                ('derivation_type', models.CharField(blank=True, choices=[('percent', 'Porcentaje'), ('amount', 'Monto')], default='percent', max_length=10)),
                ('derivation_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meal_plan', models.CharField(choices=[('room_only', 'Solo alojamiento'), ('breakfast', 'Con desayuno'), ('half_board', 'Media pensión'), ('full_board', 'Pensión completa'), ('all_inclusive', 'Todo incluido')], default='room_only', max_length=20)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_public', models.BooleanField(default=True)),
                ('channels', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('min_los_default', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cancellation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_plans', to='rates.cancellationpolicy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='rates.rateplan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='core.property')),
                ('room_types', models.ManyToManyField(blank=True, related_name='rate_plans', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje'), ('amount', 'Monto por noche')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('stay_from', models.DateField(blank=True, null=True)),
                ('stay_to', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='core.property')),
                ('rate_plans', models.ManyToManyField(blank=True, related_name='promo_codes', to='rates.rateplan')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('extra_adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('extra_child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_los', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_los', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('stop_sell', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('default', 'Por defecto'), ('season', 'Temporada'), ('manual', 'Manual'), ('revenue', 'Revenue'), ('bulk', 'Edición masiva'), ('channel', 'Canal')], default='manual', max_length=10)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='inventory.roomtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='rates.rateplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeRateDefaults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dow_adjustments', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('extra_adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_child_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('child_age_limit', models.PositiveSmallIntegerField(default=12)),
                ('single_occupancy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_defaults', to='rates.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_defaults', to='inventory.roomtype')),
            ],
            options={
                'verbose_name_plural': 'room type rate defaults',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.SmallIntegerField(default=0)),
                ('color', models.CharField(default='#B98A2E', max_length=7)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dow_adjustments', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rates', to='rates.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rates', to='inventory.roomtype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.season')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(choices=[('room', 'Alojamiento'), ('extras', 'Extras'), ('all', 'Todo')], default='room', max_length=10)),
                ('included_in_price', models.BooleanField(default=False)),
                ('exempt_foreign_non_residents', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'taxes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('charge_type', models.CharField(choices=[('per_stay', 'Por estadía'), ('per_night', 'Por noche'), ('per_person', 'Por persona'), ('per_person_night', 'Por persona por noche')], default='per_stay', max_length=20)),
                ('sellable_online', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.property')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='rates.tax')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='rate_plan_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'base'), ('parent__isnull', True)), models.Q(('kind', 'derived'), ('parent__isnull', False)), _connector='OR'), name='rate_plan_parent_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='promo_code_unique'),
        ),
        migrations.AddIndex(
            model_name='dailyrate',
            index=models.Index(fields=['rate_plan', 'date'], name='daily_rate_plan_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyrate',
            constraint=models.UniqueConstraint(fields=('room_type', 'rate_plan', 'date'), name='daily_rate_unique'),
        ),
        migrations.AddConstraint(
            model_name='roomtyperatedefaults',
            constraint=models.UniqueConstraint(fields=('room_type', 'rate_plan'), name='room_type_rate_defaults_unique'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='season_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='seasonrate',
            constraint=models.UniqueConstraint(fields=('season', 'room_type', 'rate_plan'), name='season_rate_unique'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='tax_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='extra_code_unique'),
        ),
    ]
