# Generated by Django 5.2.17 on 2026-09-26 01:55

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('guests', '0001_initial'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio_type', models.CharField(choices=[('guest', 'Huésped'), ('master', 'Maestro'), ('house', 'Casa')], default='guest', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=10)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='guests.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='core.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='folios', to='bookings.reservation')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='folios', to='bookings.stay')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('kind', models.CharField(choices=[('room', 'Alojamiento'), ('extra', 'Extra'), ('tax', 'Impuesto'), ('fee', 'Cargo'), ('cancellation_fee', 'Penalidad de cancelación'), ('adjustment', 'Ajuste'), ('other', 'Otro')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('night_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='user', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='rates.extra')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='bookings.stay')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='rates.tax')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='finance.folio')),
            ],
            options={
                'ordering': ['business_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card_terminal', 'Datáfono'), ('bank_transfer', 'Transferencia'), ('wompi_card', 'Wompi · tarjeta'), ('wompi_pse', 'Wompi · PSE'), ('wompi_nequi', 'Wompi · Nequi'), ('wompi_other', 'Wompi · otro'), ('ota_collect', 'Cobrado por la OTA'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='pending', max_length=10)),
                ('provider', models.CharField(default='manual', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('provider_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('business_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.folio')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('provider', models.CharField(max_length=30)),
                ('mode', models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulado')], default='simulated', max_length=10)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('checkout_url', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('expired', 'Expirado'), ('error', 'Error')], default='created', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('return_url', models.CharField(blank=True, max_length=1000)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='finance.folio')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='finance.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['property', 'status'], name='folio_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['folio', 'kind'], name='charge_folio_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['stay', 'night_date'], name='charge_stay_night_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['business_date'], name='charge_business_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_reference'], name='payment_provider_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['property', 'status'], name='intent_property_status_idx'),
        ),
    ]
