# Generated by Django 5.2.17 on 2026-09-28 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('corporate', '0001_initial'),
        ('finance', '0002_b4_intents_refunds_cash_shifts'),
        ('guests', '0003_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='corporate.company'),
        ),
        migrations.AddField(
            model_name='folio',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='folio',
            name='folio_type',
            field=models.CharField(choices=[('guest', 'Huésped'), ('master', 'Maestro'), ('house', 'Casa'), ('company', 'Empresa')], default='guest', max_length=10),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['company', 'status'], name='folio_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folio_type', 'company'), _negated=True), ('company__isnull', False), _connector='OR'), name='folio_company_required'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_type', 'company'), ('reservation__isnull', False)), fields=('reservation', 'company'), name='folio_one_company_folio_per_reservation'),
        ),
    ]
