# Generated by Django 5.2.17 on 2026-09-27 07:07

import apps.distribution.models
import django.core.serializers.json
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_code', models.CharField(choices=[('booksim', 'BookSim'), ('airsim', 'AirSim'), ('ical', 'iCal'), ('channex', 'Channex')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('error', 'Con error')], default='active', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to='core.property')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AriUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('kinds', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('response', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ari_updates', to='core.property')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ari_updates', to='rates.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ari_updates', to='inventory.roomtype')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ari_updates', to='distribution.channelconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_rate_id', models.CharField(blank=True, max_length=120)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_mappings', to='distribution.channelconnection')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_mappings', to='rates.rateplan')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_rate_mappings', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_room_id', models.CharField(blank=True, max_length=120)),
                ('ical_import_url', models.URLField(blank=True, max_length=1000)),
                ('ical_export_token', models.CharField(default=apps.distribution.models.new_export_token, max_length=64, unique=True)),
                ('ical_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('ical_last_error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mappings', to='distribution.channelconnection')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='inventory.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='inventory.roomtype')),
            ],
            options={
                'ordering': ['room_type__sort_order', 'room_type__code', 'room__number'],
            },
        ),
        migrations.CreateModel(
            name='ExternalReservationMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_maps', to='distribution.channelconnection')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_maps', to='bookings.reservation')),
                ('room_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_maps', to='distribution.roommapping')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimOtaBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('modified', 'Modificada'), ('cancelled', 'Cancelada')], default='new', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('pms_status', models.CharField(choices=[('pending', 'Pendiente'), ('imported', 'Importada'), ('failed', 'Falló')], default='pending', max_length=10)),
                ('pms_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_bookings', to='distribution.channelconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimOtaInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_room_id', models.CharField(max_length=120)),
                ('external_rate_id', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('available', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_los', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_los', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('stop_sell', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_inventory', to='distribution.channelconnection')),
            ],
            options={
                'ordering': ['external_room_id', 'external_rate_id', 'date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('kind', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('success', 'Correcto'), ('warning', 'Advertencia'), ('error', 'Error'), ('skipped', 'Sin cambios')], default='success', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='distribution.channelconnection')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_logs', to='bookings.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='channelconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_code', 'ical'), _negated=True), fields=('property', 'channel_code'), name='channel_connection_unique_per_property'),
        ),
        migrations.AddIndex(
            model_name='ariupdate',
            index=models.Index(fields=['status', 'next_attempt_at'], name='ari_update_due_idx'),
        ),
        migrations.AddIndex(
            model_name='ariupdate',
            index=models.Index(fields=['connection', 'room_type', 'status'], name='ari_update_coalesce_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('rate_plan__isnull', False)), fields=('connection', 'rate_plan', 'room_type'), name='rate_mapping_unique_plan', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='roommapping',
            constraint=models.UniqueConstraint(fields=('connection', 'room_type', 'room'), name='room_mapping_unique_unit', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='roommapping',
            constraint=models.UniqueConstraint(condition=models.Q(('external_room_id', ''), _negated=True), fields=('connection', 'external_room_id'), name='room_mapping_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='externalreservationmap',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='external_reservation_unique_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='simotabooking',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='sim_ota_booking_unique'),
        ),
        migrations.AddIndex(
            model_name='simotainventory',
            index=models.Index(fields=['connection', 'date'], name='sim_ota_inventory_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='simotainventory',
            constraint=models.UniqueConstraint(fields=('connection', 'external_room_id', 'external_rate_id', 'date'), name='sim_ota_inventory_unique_cell'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['connection', '-created_at'], name='sync_log_connection_idx'),
        ),
    ]
