# Generated by Django 5.2.17 on 2026-09-26 01:55

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('PEP', 'Permiso especial de permanencia'), ('PPT', 'Permiso por protección temporal'), ('DNI', 'Documento nacional de identidad'), ('NIT', 'NIT'), ('OTHER', 'Otro')], max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('country_of_residence', models.CharField(blank=True, max_length=2)),
                ('city_of_residence', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Otro')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='es', max_length=5)),
                ('is_vip', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('notes', models.TextField(blank=True)),
                ('preferences', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('data_processing_consent_at', models.DateTimeField(blank=True, null=True)),
                ('custom_values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('blacklisted', models.BooleanField(default=False)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_guests', to='guests.guest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('id_front', 'Documento (frente)'), ('id_back', 'Documento (reverso)'), ('passport', 'Pasaporte'), ('signature', 'Firma'), ('other', 'Otro')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='guest-documents/%Y/%m/')),
                ('uploaded_via', models.CharField(choices=[('staff', 'Recepción'), ('portal', 'Portal del huésped')], default='staff', max_length=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'email'], name='guest_org_email_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'phone'], name='guest_org_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'last_name'], name='guest_org_last_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'document_type', 'document_number'), name='guest_document_unique'),
        ),
    ]
