# Generated by Django 5.2.17 on 2026-09-26 03:50

import apps.guests.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestdocument',
            name='file',
            field=models.FileField(max_length=255, storage=apps.guests.storage.PrivateDocumentStorage(), upload_to=apps.guests.storage.document_upload_to),
        ),
    ]
