# Generated by Django 5.2.17 on 2026-09-27 21:10

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('description', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('max_units', models.PositiveIntegerField(blank=True, null=True)),
                ('max_properties', models.PositiveIntegerField(blank=True, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('subscription', 'Suscripción'), ('commissions', 'Comisiones'), ('other', 'Otro')], default='subscription', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('lines', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('paid', 'Pagada'), ('void', 'Anulada'), ('failed', 'Cobro fallido')], default='open', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('payment_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pdf', models.FileField(blank=True, upload_to='platform-invoices/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='core.organization')),
            ],
            options={
                'ordering': ['-issued_at', '-number'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('commissions_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('invoiced', 'Facturada'), ('paid', 'Pagada')], default='open', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_settlements', to='core.organization')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='saas.platforminvoice')),
            ],
            options={
                'ordering': ['-period_start', 'organization__name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'En mora'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=10)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('payment_source', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas.plan')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(choices=[('stay', 'Alojamiento'), ('fee', 'Penalidad')], default='stay', max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('settled', 'Liquidada'), ('reversed', 'Revertida')], default='pending', max_length=10)),
                ('accrual_date', models.DateField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.property')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_commission', to='bookings.reservation')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='saas.commissionsettlement')),
            ],
            options={
                'ordering': ['-accrual_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'accrual_date'], name='saas_comm_org_status_idx'), models.Index(fields=['accrual_date'], name='saas_comm_accrual_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['organization', 'status'], name='saas_invoice_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.UniqueConstraint(fields=('organization', 'period_start'), name='saas_settlement_org_month'),
        ),
    ]
