# Generated by Django 5.2.17 on 2026-09-27 07:16

import apps.compliance.storage
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0002_b4_intents_refunds_cash_shifts'),
        ('guests', '0003_unaccent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_issue_invoices', models.BooleanField(default=True)),
                ('final_consumer_id', models.CharField(default='222222222222', max_length=20)),
                ('invoice_notes', models.TextField(blank=True)),
                ('sire_establishment_code', models.CharField(blank=True, max_length=20)),
                ('sire_city_code', models.CharField(blank=True, max_length=10)),
                ('sire_document_codes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sire_country_codes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sire_second_surname_column', models.BooleanField(default=False)),
                ('tra_auto_register', models.BooleanField(default=True)),
                ('tra_establishment_id', models.CharField(blank=True, max_length=30)),
                ('tra_travel_reason', models.CharField(default='Vacaciones, recreo y ocio', max_length=80)),
                ('tra_accommodation_type', models.CharField(blank=True, max_length=60)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_settings', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'compliance settings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_kind', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota crédito')], default='invoice', max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('resolution_number', models.CharField(blank=True, max_length=40)),
                ('from_number', models.PositiveBigIntegerField()),
                ('to_number', models.PositiveBigIntegerField()),
                ('current_number', models.PositiveBigIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('technical_key', models.CharField(blank=True, max_length=128)),
                ('environment', models.CharField(choices=[('test', 'Pruebas (habilitación)'), ('production', 'Producción')], default='test', max_length=20)),
                ('provider_range_id', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_resolutions', to='core.property')),
            ],
            options={
                'ordering': ['document_kind', '-is_active', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota crédito')], default='invoice', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Anulada'), ('error', 'Error')], default='draft', max_length=20)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('full_number', models.CharField(blank=True, max_length=40)),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('customer', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('lines', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exempt_note', models.CharField(blank=True, max_length=255)),
                ('cufe', models.CharField(blank=True, max_length=128)),
                ('qr_data', models.TextField(blank=True)),
                ('xml_file', models.FileField(blank=True, max_length=255, storage=apps.compliance.storage.ComplianceStorage(), upload_to=apps.compliance.storage.invoice_upload_to)),
                ('pdf_file', models.FileField(blank=True, max_length=255, storage=apps.compliance.storage.ComplianceStorage(), upload_to=apps.compliance.storage.invoice_upload_to)),
                ('mode', models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulado')], default='simulated', max_length=10)),
                ('environment', models.CharField(choices=[('test', 'Pruebas (habilitación)'), ('production', 'Producción')], default='test', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('provider_response', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('reason', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('charges', models.ManyToManyField(blank=True, related_name='invoices', to='finance.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='finance.folio')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.property')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='credit_notes', to='compliance.invoice')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='bookings.reservation')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='compliance.invoiceresolution')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SireReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, max_length=255, storage=apps.compliance.storage.ComplianceStorage(), upload_to=apps.compliance.storage.sire_upload_to)),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('submitted', 'Reportado'), ('acknowledged', 'Con acuse')], default='generated', max_length=20)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('missing', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('mode', models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulado')], default='simulated', max_length=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ack_code', models.CharField(blank=True, max_length=80)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire_reports', to='core.property')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SireRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('movement_date', models.DateField()),
                ('complete', models.BooleanField(default=True)),
                ('missing_fields', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sire_records', to='guests.guest')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sire_records', to='bookings.stay')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='compliance.sirereport')),
            ],
            options={
                'ordering': ['movement_date', 'movement', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_main', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('registered', 'Registrado'), ('error', 'Error')], default='pending', max_length=20)),
                ('tra_number', models.CharField(blank=True, max_length=60)),
                ('mode', models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulado')], default='simulated', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('response', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('missing_fields', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tra_registrations', to='guests.guest')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='compliance.traregistration')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tra_registrations', to='core.property')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tra_registrations', to='bookings.reservation')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tra_registrations', to='bookings.stay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('to_number__gte', models.F('from_number'))), name='resolution_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='resolution_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('property', 'document_kind'), name='resolution_one_active_per_kind'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['property', 'status'], name='invoice_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['property', '-issue_date'], name='invoice_property_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('property', 'kind', 'prefix', 'number'), name='invoice_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='sirereport',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='sire_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='sirerecord',
            constraint=models.UniqueConstraint(fields=('report', 'stay', 'guest', 'movement'), name='sire_record_unique_movement'),
        ),
        migrations.AddIndex(
            model_name='traregistration',
            index=models.Index(fields=['property', 'status'], name='tra_property_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='traregistration',
            constraint=models.UniqueConstraint(fields=('stay', 'guest'), name='tra_stay_guest_unique'),
        ),
    ]
