# Generated by Django 5.2.17 on 2026-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancesettings',
            name='go_live_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
