# Generated by Django 5.2.17 on 2026-09-28 11:51

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('guests', 'Huéspedes'), ('reservations', 'Reservas'), ('room_types', 'Categorías'), ('rooms', 'Habitaciones')], max_length=20)),
                ('preset', models.CharField(choices=[('generic', 'Genérico'), ('cloudbeds', 'Export de Cloudbeds')], default='generic', max_length=20)),
                ('source_system', models.CharField(max_length=60)),
                ('source_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Por mapear'), ('validated', 'Revisado'), ('queued', 'En cola'), ('running', 'En proceso'), ('completed', 'Completado'), ('failed', 'Falló'), ('reverted', 'Revertido')], default='uploaded', max_length=20)),
                ('phase', models.CharField(blank=True, choices=[('', '—'), ('dry_run', 'Simulación'), ('run', 'Importación'), ('revert', 'Reversión')], default='', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
                ('headers', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('mapping', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('value_map', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('options', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('counts', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('dry_run_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run_summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('revert_summary', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('data_purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.property')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('guests', 'Huéspedes'), ('reservations', 'Reservas'), ('room_types', 'Categorías'), ('rooms', 'Habitaciones')], max_length=20)),
                ('source_system', models.CharField(max_length=60)),
                ('external_id', models.CharField(max_length=200)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.UUIDField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.property')),
                ('created_by_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='imports.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('raw', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('group_key', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Sin revisar'), ('valid', 'Lista'), ('warning', 'Con advertencias'), ('error', 'Con errores'), ('skip', 'Se omite')], default='pending', max_length=10)),
                ('issues', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('dry_outcome', models.CharField(blank=True, choices=[('', '—'), ('create', 'Se crearía'), ('update', 'Se actualizaría'), ('skip', 'Se omitiría'), ('fail', 'Fallaría')], default='', max_length=10)),
                ('dry_message', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('outcome', models.CharField(blank=True, choices=[('', '—'), ('created', 'Creado'), ('updated', 'Actualizado'), ('skipped', 'Omitido'), ('failed', 'Con error'), ('reverted', 'Revertido')], default='', max_length=10)),
                ('outcome_message', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=160)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['property', '-created_at'], name='import_job_prop_created_idx'),
        ),
        migrations.AddIndex(
            model_name='importedrecord',
            index=models.Index(fields=['target_type', 'target_id'], name='imported_record_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedrecord',
            constraint=models.UniqueConstraint(fields=('property', 'kind', 'source_system', 'external_id'), name='imported_record_unique'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status'], name='import_row_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'outcome'], name='import_row_job_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['target_type', 'target_id'], name='import_row_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'number'), name='import_row_job_number_unique'),
        ),
    ]
